--- #YAML:1.0
name:                Class-DBI-Lite
version:             1.032
abstract:            Lightweight ORM for Perl
license:             Perl
author:              
    - John Drago <jdrago_999@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBD::SQLite:                   0
    DBI:                           0
    Ima::DBI::Contextual:          1.004
    SQL::Abstract:                 0
    SQL::Abstract::Limit:          0
    Test::Memory::Cycle:           0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
